version: '3.9'
services:
  api:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - timescaledb

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_DB: ohlc_db
      POSTGRES_USER: ohlc_user
      POSTGRES_PASSWORD: ohlc_pass
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5050:80"
    depends_on:
      - timescaledb

volumes:
  timescale_data:
